"use client";
import { useRef, useState } from 'react';
import { ArrowUpRight, CircleDollarSign, Download, FileCheck2, FlaskConical, Pause, Play, RotateCcw, Upload, Users } from 'lucide-react';
import { demoRows } from './demo-data';
import { costRow, summarize, projectRevenue, parseProduction, defaultScenario, initialWorkforce, workforceAction, gross, payrollCSV, type Employee, type ProductionRow } from './engine';

const usd=(n:number|null)=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const num=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
const time=(minute:number)=>`${String(Math.floor(minute/60)%24).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}`;
function download(name:string,contents:string,type:string) {const url=URL.createObjectURL(new Blob([contents],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function useOperationsDemo() {
  const [rows,setRows]=useState<ProductionRow[]>(demoRows);
  const [resetVersion,setResetVersion]=useState(0);
  const [privateData,setPrivate]=useState(false);
  const [workforce,setWorkforce]=useState(initialWorkforce);
  const [scenario,setScenario]=useState({...defaultScenario});
  const [from,setFrom]=useState('2026-08-01'),[to,setTo]=useState('2026-09-30'),[product,setProduct]=useState('all');
  function reset(){setRows(demoRows);setPrivate(false);setWorkforce(initialWorkforce());setScenario({...defaultScenario});setFrom('2026-08-01');setTo('2026-09-30');setProduct('all');setResetVersion(v=>v+1);}
  return {rows,setRows,privateData,setPrivate,workforce,setWorkforce,scenario,setScenario,from,setFrom,to,setTo,product,setProduct,reset,resetVersion};
}
type Demo=ReturnType<typeof useOperationsDemo>;
function Stat({label,value,note,tone=''}:{label:string;value:string;note:string;tone?:string}){return <article className={`op-stat ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>;}
function Intro({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:React.ReactNode}){return <div className="op-intro"><div><p className="section-kicker">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div><div className="op-actions">{children}</div></div>;}

export function CostsStudio({demo}:{demo:Demo}) {
  const {rows,privateData,from,to,product,scenario}=demo;
  const [tab,setTab]=useState('costs'),[error,setError]=useState('');
  const file=useRef<HTMLInputElement>(null);
  const selected=rows.filter(r=>r.date>=from&&r.date<=to&&(product==='all'||r.product===product));
  const total=summarize(selected),forecast=projectRevenue(total,scenario);
  const reviewed=selected.map(r=>costRow(r));
  const anomalies=rows.filter(r=>r.date<'2026-01-01'||r.date>'2026-12-31');
  const incomplete=rows.map(r=>costRow(r)).filter(r=>!r.value);
  const reconciliations=rows.flatMap(r=>{const c=costRow(r).value;return c&&r.source?(['P','Y','AF','AG','AI'] as const).flatMap(k=>{const computed={P:c.productionValue,Y:c.labor,AF:c.appliedOverhead,AG:c.cost,AI:c.result}[k];return typeof r.source![k]==='number'&&Math.abs(r.source![k]!-computed)>.01?[{row:r.sourceRow,field:k,difference:computed-r.source![k]!}]:[]}):[];});
  async function load(f:File|undefined){if(!f)return;try{if(f.size>5_000_000)throw new Error('File too large (5 MB maximum).');const parsed=parseProduction(await f.text());demo.setRows(parsed);demo.setPrivate(true);demo.setProduct('all');setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to read file');}finally{if(file.current)file.current.value='';}}
  return <div className="op-screen">
    <Intro eyebrow="Operational economics" title="Know the cost. See the upside." description="Production costing and transparent revenue scenarios, from batch to business.">
      <input ref={file} type="file" accept=".json" className="op-hidden" aria-label="Load normalized production JSON" onChange={e=>void load(e.target.files?.[0])}/>
      <button onClick={()=>file.current?.click()}><Upload size={16}/> Load Charles’s data</button>
    </Intro>
    <div className="op-notice"><FileCheck2 size={17}/><span>{privateData?'Private workbook loaded in browser memory · Main Production':'Fictional demo data · load the supplied private JSON to review Charles’s workbook'} · USD assumed · no live integration</span></div>
    {error&&<p role="alert" className="op-error">{error}</p>}
    {tab==='source'&&rows.some(r=>r.rawIssues?.length)&&<p className="op-notice">Source text preserved as missing numeric input: {rows.flatMap(r=>r.rawIssues??[]).join(' · ')}</p>}
    <div className="op-toolbar"><div className="op-tabs" role="tablist" aria-label="Economics views">{[['costs','Production costs'],['scenario','Revenue scenario'],['source','Source checks']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="op-filters"><label>From<input type="date" value={from} onChange={e=>demo.setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>demo.setTo(e.target.value)}/></label><label>Product<select value={product} onChange={e=>demo.setProduct(e.target.value)}><option value="all">All products</option>{[...new Set(rows.map(r=>r.product))].sort().map(p=><option key={p}>{p}</option>)}</select></label></div></div>
    {from>to&&<p role="alert" className="op-error">Choose an end date after the start date.</p>}
    <div className="op-kpis"><Stat label="Production sales value" value={usd(total.value)} note="Output × unit selling price"/><Stat label="Full production cost" value={usd(total.cost)} note="Materials + labor + applied overhead"/><Stat label="Modeled production result" value={usd(total.value-total.cost)} note="Not booked sales or accounting net profit" tone={total.value<total.cost?'negative':'positive'}/><Stat label="Costing coverage" value={`${total.included} / ${selected.length}`} note={`${total.excluded} incomplete batches excluded`}/></div>
    {tab==='costs'&&<>
      <div className="op-columns"><section className="op-panel"><p className="section-kicker">Cost composition</p><h2>Where the money goes</h2>{[['Materials',total.material],['Direct labor',total.labor],['Applied overhead',total.overhead]].map(([label,value])=><div className="op-bar-row" key={label}><div><span>{label}</span><strong>{usd(Number(value))}</strong></div><div className="op-bar"><span style={{width:`${total.cost?Number(value)/total.cost*100:0}%`}}/></div></div>)}<p className="op-note">Workbook basis: overhead = direct labor × 135%. Blank overtime, double time and loose pieces are treated as zero. Missing core costs remain incomplete.</p></section>
      <section className="op-panel op-insight"><FlaskConical/><p className="section-kicker">Decision insight · calculated locally</p><h2>{reviewed.filter(r=>r.value&&r.value.result<0).length} batches below modeled break-even</h2><p>Explore price, production volume and sell-through before committing the next run.</p><button onClick={()=>setTab('scenario')}>Open revenue scenario <ArrowUpRight size={17}/></button><p className="op-note">Rule-based analysis. No AI service is connected.</p></section></div>
      <section className="op-panel"><div className="op-panel-heading"><div><p className="section-kicker">Batch economics</p><h2>Every batch, explained</h2></div><span className="op-pill">{selected.length} rows in scope</span></div><div className="op-table-wrap"><table><thead><tr><th>Product / source</th><th>Cases / loose units</th><th>Materials</th><th>Labor</th><th>Overhead</th><th>Production value</th><th>Result / margin</th></tr></thead><tbody>{reviewed.map(({row:r,value:v,issues})=><tr key={r.id}><td><details><summary><strong>{r.product}</strong><small>{r.date} · row {r.sourceRow}</small></summary><div className="op-detail">Lot {r.lot} · SKU {r.sku}<br/>Case pack: {r.unitsPerCase??'missing'} units<br/>Material variance: {usd(v?.materialVariance??null)}<br/>Labor variance: {usd(v?.laborVariance??null)}<br/>Positive variance = favorable. Standard labor follows the worksheet’s per-case formula; source header says per unit.<br/>{r.comment}</div></details></td><td>{r.producedCases??'—'} / {r.looseUnits??0}</td><td>{usd(r.material)}</td><td>{usd(v?.labor??null)}</td><td>{usd(v?.appliedOverhead??null)}</td><td>{usd(v?.productionValue??null)}</td><td className={v&&v.result<0?'op-loss':'op-gain'}>{v?<><strong>{usd(v.result)}</strong><small>{v.margin==null?'No sales value':`${(v.margin*100).toFixed(1)}%`}</small></>:<span title={issues.join('; ')}>Incomplete</span>}</td></tr>)}</tbody></table>{!selected.length&&<p className="op-note">No batches in this scope.</p>}</div></section>
    </>}
    {tab==='scenario'&&<div className="op-columns op-scenario"><section className="op-panel"><p className="section-kicker">What if?</p><h2>Build the next scenario</h2><p className="op-note">Based on the complete batches in the selected period. Linear assumptions, without demand history or capacity optimization.</p>{([{key:'volume',label:'Production volume',min:0,max:150},{key:'price',label:'Selling price change',min:-30,max:30},{key:'sellThrough',label:'Expected sell-through',min:0,max:100},{key:'materials',label:'Material cost change',min:-20,max:40},{key:'labor',label:'Labor intensity change',min:-20,max:50}] as const).map(c=><label className="op-slider" key={c.key}><span>{c.label}<strong>{scenario[c.key]}%</strong></span><input type="range" min={c.min} max={c.max} value={scenario[c.key]} onChange={e=>demo.setScenario({...scenario,[c.key]:Number(e.target.value)})}/></label>)}<button onClick={()=>demo.setScenario({...defaultScenario})}><RotateCcw size={15}/> Reset assumptions</button></section><section className="op-panel op-scenario-result"><p className="section-kicker">Scenario estimate</p><h2>{usd(forecast.revenue)}</h2><p>Expected revenue from units expected to sell</p><div className="op-result-line"><span>Planned production spend</span><strong>{usd(forecast.spend)}</strong></div><div className="op-result-line"><span>Revenue less production spend</span><strong className={forecast.balance<0?'op-loss':'op-gain'}>{usd(forecast.balance)}</strong></div><div className="op-result-line"><span>Produced / expected sold</span><strong>{num(forecast.producedUnits)} / {num(forecast.soldUnits)}</strong></div><div className="op-result-line"><span>Unsold units</span><strong>{num(forecast.remainingUnits)}</strong></div><p className="op-note">Unsold units are not revenue. This compares revenue with the full production spend; it is not an accounting profit or cash-flow forecast. Inventory valuation, spoilage, returns, discounts, payment timing and selling costs need separate rules.</p><p className="op-note">Labor and its 135% overhead allocation scale with volume and labor intensity. Paid rest does not reduce paid hours. Workforce demo timecards are separate from historical batch costs.</p><button disabled={!total.included} onClick={()=>download('o7-revenue-scenario.json',JSON.stringify({kind:'demo-scenario',scope:{from,to,product},source:privateData?'private-workbook':'fictional',assumptions:scenario,result:forecast},null,2),'application/json')}><Download size={16}/> Export scenario</button></section></div>}
    {tab==='source'&&<section className="op-panel"><p className="section-kicker">Data before decisions</p><h2>Source checks & assumptions</h2><ul className="op-checks"><li><strong>{rows.length} product rows loaded</strong><span>Main Production only. Sheet3 is an archive with a different layout and is not merged.</span></li><li><strong>{anomalies.length} dates outside 2026</strong><span>{anomalies.map(r=>`row ${r.sourceRow}: ${r.date}`).join(' · ')||'None'}. Source dates are preserved. Default filters exclude them.</span></li><li><strong>{incomplete.length} rows lack a complete cost basis</strong><span>{incomplete.slice(0,10).map(r=>`row ${r.row.sourceRow}: ${r.issues.join(', ')}`).join(' · ')||'No missing core inputs.'}</span></li><li><strong>{privateData?reconciliations.length:'—'} differences versus cached Excel totals</strong><span>{privateData?reconciliations.slice(0,8).map(r=>`row ${r.row}, ${r.field}: ${usd(r.difference)}`).join(' · ')||'Complete rows reconcile within $0.01 for sales value, labor, overhead, total cost and result.':'Load Charles’s file to reconcile cached values.'}</span></li><li><strong>Units must be confirmed</strong><span>Column Z says “per unit”; column AA multiplies it by cases. Product weight units are not explicit, so no weight-based costing is inferred.</span></li><li><strong>Overhead is an allocation</strong><span>The workbook uses 135% of labor. Sheet2 derives about 135.435%. Confirm periods and scope before changing this factor; employer taxes appear in the labor base and must not be counted twice.</span></li><li><strong>No actual sales history in this file</strong><span>Production value is not invoiced revenue. Forecasting requires historical orders, prices, cancellations, sell-through and delivery dates.</span></li></ul></section>}
  </div>;
}

export function WorkforceStudio({demo}:{demo:Demo}) {
  const {workforce:w,setWorkforce}=demo;
  const [editing,setEditing]=useState<string|null>(null),[reason,setReason]=useState(''),[draft,setDraft]=useState({regular:0,ot:0,double:0,rate:22});
  const [message,setMessage]=useState('');
  const act=(id:string,action:Parameters<typeof workforceAction>[2])=>setWorkforce(s=>workforceAction(s,id,action));
  const onBreak=w.people.filter(e=>e.status==='paid-rest'||e.status==='unpaid-meal');
  function edit(e:Employee){setEditing(e.id);setDraft({regular:e.regular,ot:e.ot,double:e.double,rate:e.rate});setReason('');}
  function save(){if(!reason.trim()||Object.values(draft).some(v=>!Number.isFinite(v)||v<0))return;setWorkforce(s=>({...s,people:s.people.map(e=>e.id===editing&&!e.approved&&e.status==='off'?{...e,...draft}:e),audit:[`${s.minute} · ${editing} · correction ${JSON.stringify(draft)} · ${reason.trim()}`,...s.audit]}));setEditing(null);}
  return <div className="op-screen"><Intro eyebrow="People & production" title="A clear view of every shift." description="Track paid rest, unpaid meals and reviewed timecards in one operational workspace."><button onClick={()=>act('','advance')}><Play size={15}/> Advance demo +15 min</button></Intro>
    <div className="op-notice"><Users size={17}/><span>Fictional employees · demo clock {time(w.minute)} · session memory only · payroll preparation, no payments or tax calculations</span></div>
    <div className="op-kpis"><Stat label="On the floor" value={String(w.people.filter(e=>e.status==='working').length)} note="Available at assigned line"/><Stat label="On a break" value={String(onBreak.length)} note="Paid rest + unpaid meal"/><Stat label="Estimated gross wages" value={usd(w.people.reduce((a,e)=>a+gross(e),0))} note="Hours × rates; no taxes or deductions"/><Stat label="Approved timecards" value={`${w.people.filter(e=>e.approved).length} / ${w.people.length}`} note="Closed and reviewed for demo export"/></div>
    <div className="op-columns"><section className="op-panel"><p className="section-kicker">Line coverage</p><h2>Keep the team in view</h2>{['Line 1','Line 2'].map(line=><div className="op-result-line" key={line}><span>{line}</span><strong>{w.people.filter(e=>e.line===line&&e.status==='working').length} / {w.people.filter(e=>e.line===line).length} working</strong></div>)}<p className="op-note">Coverage is informational. Required staffing and staggered break rules will be configured with the team.</p></section><section className="op-panel op-insight"><Pause/><p className="section-kicker">Breaks with context</p><h2>Paid rest stays paid.</h2><p>The demo clock adds paid time while working or on paid rest. Unpaid meal time is recorded separately.</p><p className="op-note">No automatic break deductions. Overtime categories are reviewed manually; jurisdiction and payroll provider rules are not configured.</p></section></div>
    <section className="op-panel"><div className="op-panel-heading"><div><p className="section-kicker">Live demo roster</p><h2>Shift & break control</h2></div><span className="op-pill">{time(w.minute)}</span></div><div className="op-table-wrap"><table><thead><tr><th>Team member</th><th>Status</th><th>Paid hours / gross</th><th>Rest / meal</th><th>Actions</th></tr></thead><tbody>{w.people.map(e=><tr key={e.id}><td><strong>{e.name}</strong><small>{e.id} · {e.line}</small></td><td><span className="op-pill">{e.approved?'Approved':e.status.replaceAll('-',' ')}</span>{e.breakStart!=null&&<small>{w.minute-e.breakStart} min elapsed</small>}</td><td><strong>{(e.regular+e.ot+e.double).toFixed(2)} h · {usd(gross(e))}</strong><small>Reg {e.regular.toFixed(2)} · OT {e.ot.toFixed(2)} · 2× {e.double.toFixed(2)}</small></td><td>{e.paidBreak} / {e.unpaidBreak} min<small>Completed breaks</small></td><td><div className="op-actions">{e.status==='working'&&<><button onClick={()=>act(e.id,'paid-rest')}>Paid rest</button><button onClick={()=>act(e.id,'unpaid-meal')}>Unpaid meal</button><button onClick={()=>act(e.id,'finish')}>End shift</button></>}{(e.status==='paid-rest'||e.status==='unpaid-meal')&&<button disabled={e.breakStart===w.minute} onClick={()=>act(e.id,'resume')}>Resume work</button>}{e.status==='off'&&!e.approved&&<><button onClick={()=>edit(e)}>Review hours</button><button onClick={()=>act(e.id,'approve')}>Approve</button></>}{e.approved&&<button onClick={()=>act(e.id,'reopen')}>Reopen review</button>}</div></td></tr>)}</tbody></table></div></section>
    {editing&&<section className="op-panel"><h2>Review {editing}</h2><p className="op-note">Explicit correction of demo hour buckets; this does not recalculate statutory overtime.</p><div className="op-filters">{(['regular','ot','double','rate'] as const).map(key=><label key={key}>{key}<input type="number" min="0" step="0.25" value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value===''?NaN:Number(e.target.value)})}/></label>)}<label>Correction reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required for audit"/></label></div><div className="op-actions"><button disabled={!reason.trim()||Object.values(draft).some(v=>!Number.isFinite(v)||v<0)} onClick={save}>Save correction</button><button onClick={()=>setEditing(null)}>Cancel</button></div></section>}
    <div className="op-columns"><section className="op-panel"><CircleDollarSign/><p className="section-kicker">Payroll preparation</p><h2>Reviewed hours, ready to hand over</h2><p>Export closed, approved timecards as a neutral CSV for discussion with the payroll provider.</p><button disabled={!w.people.some(e=>e.approved)} onClick={()=>{download('o7-DEMO-payroll-preparation.csv',payrollCSV(w.people),'text/csv;charset=utf-8');setMessage('Demo CSV exported. No payroll was submitted.');}}><Download size={16}/> Export approved timecards</button><p role="status" className="op-note">{message||'Restaurant365 and Toast adapters are not connected. No provider-specific import format is claimed.'}</p></section><section className="op-panel"><p className="section-kicker">Review history</p><h2>Every change leaves a trace</h2><div className="op-audit">{w.audit.length?w.audit.map((a,i)=><p key={i}>{a}</p>):<p>Start a break or end a shift to create the first event.</p>}</div><p className="op-note">In-memory demo log. Production requires authenticated actors, durable events and access controls.</p></section></div>
  </div>;
}
